version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: section7db
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:8.4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: brackcat09@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8050:80"
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin4-data: