services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5174:5173"
    environment:
      - PORT=5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev